// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type LoginInput struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type MeetupFilter struct {
	Name *string `json:"name"`
}

type NewMeetup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage"`
}

type PlaceConnection struct {
	Edges    []*PlaceEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type PlaceEdge struct {
	Cursor string `json:"cursor"`
	Node   *Place `json:"node"`
}

type PlaceFilter struct {
	Name *string `json:"name"`
}

type PlaceInput struct {
	Address     string `json:"address"`
	Description string `json:"description"`
	Name        string `json:"name"`
	OrderNumber int    `json:"orderNumber"`
	Published   bool   `json:"published"`
}

type PlacePayload struct {
	Place *Place `json:"place"`
	ID    string `json:"id"`
}

type RegisterInput struct {
	Phone           string `json:"phone"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
}

type UpdateMeetup struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}
